<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Phalcon PHP Framework</title>
    <link rel="stylesheet" href="/assets/css/vendor.css">
    <link rel="stylesheet" href="/assets/css/vendor.sass.css">
</head>
<body>
<div class="container">

    <div class="page-header">
        <h1>Hello here!</h1>
        <?php echo $this->getContent(); ?>
    </div>

    <p>You're now flying with Phalcon. Great things are about to happen!</p>

    <p>This page is located at <code>views/index.phtml</code></p>
</div>
<script src="/assets/js/vendor.js"></script>
</body>
</html>
