<!-- views/index.phtml -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title><?php echo $title; ?></title>
    <link rel="stylesheet" href="/assets/css/vendor.css">
    <link rel="stylesheet" href="/assets/css/vendor.sass.css">
    <?php $this->assets->outputCss(); ?>
</head>
<body>
<div class="container" id="formContainer">
    <div class="d-flex flex-row justify-content-center p-4">
        <?php echo $this->getContent(); ?>
    </div>

</div>
<script src="/assets/js/vendor.js"></script>
<?php $this->assets->outputJs(); ?>
</body>
</html>
<!-- end views/index.phtml -->
